FROM python:3.10-slim

# Atualizar e instalar dependências
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    libnss3 \
    libxss1 \
    libasound2 \
    fonts-liberation \
    libappindicator3-1 \
    libgbm-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar o Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install \
    && rm google-chrome-stable_current_amd64.deb

    # Verificar se o binário do Chrome está no PATH.
RUN which google-chrome-stable

# Configurar diretório de trabalho
WORKDIR /app

# Instalar dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expor porta para o Flask
EXPOSE 5000

# Comando final para rodar o app
COPY . .
CMD ["python", "run.py"]