# Use uma imagem base do Python (versão 3.9, por exemplo)
FROM python:3.9-slim

# Instala dependências do sistema e o Chrome
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

# Instala o ChromeDriver
RUN pip install -U selenium webdriver-manager

# Cria o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto para o contêiner
COPY . /app

# Instala as dependências do Python do projeto
RUN pip install -r requirements.txt

# Comando para rodar a aplicação (ajuste conforme seu script principal)
CMD ["python", "main.py"]