FROM python:3.10-slim

# Atualizar e instalar dependências
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    libnss3 \
    libxss1 \
    libasound2 \
    fonts-liberation \
    libappindicator3-1 \
    libgbm-dev \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

# Verificar se o binário do Chromium e do ChromeDriver estão no PATH.
RUN which chromium && which chromedriver

# Configurar diretório de trabalho
WORKDIR /app

# Instalar dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Adicionar caminho do ChromeDriver no PATH
ENV PATH="/usr/bin:${PATH}"

# Expor porta para o Flask
EXPOSE 5000

# Comando final para rodar o app
COPY . .
CMD ["python", "run.py"]